service: serverless-2024-prova
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role: arn:aws:iam::730335410292:role/LabRole
  
  environment:
    DB_HOST: "uf12-rds.cla48osiutwd.us-east-1.rds.amazonaws.com"
    DB_PORT: 3306
    DB_USER: "admin"
    DB_PASSWORD: "Astore63!"
    DB_NAMEDB: "afp_ps"


functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /hello
          method: get

  goodbye:
    handler: src/handler.goodbye
    events:
      - httpApi:
          path: /goodbye
          method: get

  getAllPatients:
    handler: src/handler_ospedale.getAllPazienti
    events:
      - httpApi:
          path: /getAllPazienti
          method: get

  getPatientById:
    handler: src/handler_ospedale.getPatientById
    events:
      - httpApi:
          path: /getPatientById/{id}
          method: get

  updatePaziente:
    handler: src/handler_ospedale.updatePaziente
    events:
      - httpApi:
          path: /updatePaziente/{id}
          method: put

  deletePaziente:
    handler: src/handler_ospedale.deletePaziente
    events:
      - httpApi:
          path: /deletePaziente/{id}
          method: delete

  createPaziente:
    handler: src/handler_ospedale.createPaziente
    events:
      - httpApi:
          path: /createPaziente
          method: post

  

plugins:
  - serverless-offline
  - serverless-plugin-typescript